# This is an easy out-of-the-box self-hosted config and comes with everything
# needed to run a yaba server. Includes Grafana that integrates for custom dashboards.
#
# A `db_password.txt` file needs to be initialized without special characters or new lines.
#
# Docker compose setup that creates:
# - Postgres instance exposed on port 5432
# - Yaba instance exposed on port 9222 running in single user mode
# - Grafana instance exposed on port 3000

services:
  web:
    image: yaba
    ports:
      - "9222:9222"
    env_file:
      - config/postgres.env
    environment:
      # All operations will be from a single unauthenticated user.
      # This configuration is for self-hosted use cases.
      - SINGLE_USER_MODE=true
      - SINGLE_USER_UUID=b49585ce-1ba0-4875-a99a-431b4c44c4d0
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres:16.3
    ports:
      - "5432:5432"
    env_file:
      - config/postgres.env
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    links:
      - db

secrets:
   db_password:
     file: db_password.txt
