version: "2"
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - gochecknoinits
    - ireturn
    - mnd
    - nolintlint
    - varnamelen
  settings:
    wsl:
      allow-cuddle-declarations: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
          - goconst
          - mnd
        path: .*_test.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
