linters:
  enable-all: true
  disable:
    - execinquery
    - gomnd
    - depguard
    - varnamelen
    - exhaustruct
    - gci
    - gofumpt
    - goimports
    - nolintlint
    - ireturn

issues:
  exclude-rules:
    - path: '.*_test.go'
      linters:
        - funlen
        - goconst
        - mnd

linters-settings:
  wsl:
    allow-cuddle-declarations: true