linters:
  enable-all: true
  disable:
    - execinquery
    - gomnd
    - depguard
    - varnamelen
    - exhaustruct
    - gci
    - gofumpt
    - goimports
    - nolintlint

issues:
  exclude-rules:
    - path: 'test/'
      linters:
        - funlen
        - goconst
        - mnd
