linters:
  enable-all: true
  disable:
    - depguard
    - varnamelen
    - exhaustruct
    - gci
    - gofumpt
    - goimports
    - nolintlint
    - ireturn
    - deadcode # Deprecated
    - execinquery # Deprecated
    - exhaustivestruct # Deprecated
    - exportloopref # Deprecated
    - golint # Deprecated
    - gomnd # Deprecated
    - ifshort # Deprecated
    - interfacer # Deprecated
    - maligned # Deprecated
    - nosnakecase # Deprecated
    - scopelint # Deprecated
    - structcheck # Deprecated
    - tenv # Deprecated
    - varcheck # Deprecated

issues:
  exclude-rules:
    - path: '.*_test.go'
      linters:
        - funlen
        - goconst
        - mnd

linters-settings:
  wsl:
    allow-cuddle-declarations: true