# Docker compose file that spins up a postgres database and a server instance.
#
# A `db_password.txt` file needs to be initialized without special characters or new lines.
volumes:
  database:
    name: yaba_database

services:
  db:
    image: postgres:16.3
    # Uncomment to expose postgres on port 5432. Disabled by default.
    ports:
      - "5432:5432"
    env_file:
      - docker.env
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    volumes:
      - database:/var/lib/postgresql/data
    secrets:
      - db_password
  yaba_server:
    image: wenbenz/yaba
    env_file:
      - docker.env
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
      - YABA_PORT=9222
      #Enabling this will prevent the 'secure' attribute from being set in cookies.
      #Uncomment if you're not planning to use HTTPS.
      #- INSECURE_COOKIE=true
    ports:
      - "9222:9222"
    secrets:
      - db_password
    links:
      - db
    depends_on:
      - db

secrets:
   db_password:
     file: db_password.txt
