services:
  web:
    image: yaba
    ports:
      - "8080:8080"
    env_file:
      - docker.env
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres:16.3
    ports:
      - "5432:5432"
    env_file:
      - docker.env
