# Docker infrastructure only config. This config only starts a postgres instance
# that can be used for debugging. For other configurations, see config/examples/docker-compose

services:
  db:
    image: postgres:16.3
    ports:
      - "5432:5432"
    env_file:
      - config/postgres.env
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password

secrets:
   db_password:
     file: db_password.txt
