services:
  web:
    image: yaba
    ports:
      - "8080:8080"

  db:
    image: postgres:16.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: yaba
      POSTGRES_PASSWORD: password
