// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Expenditure struct {
	ID             *string `json:"id,omitempty"`
	Owner          *string `json:"owner,omitempty"`
	Name           *string `json:"name,omitempty"`
	Amount         *string `json:"amount,omitempty"`
	Date           *string `json:"date,omitempty"`
	Method         *string `json:"method,omitempty"`
	BudgetCategory *string `json:"budget_category,omitempty"`
	RewardCategory *string `json:"reward_category,omitempty"`
	Comment        *string `json:"comment,omitempty"`
	Created        *string `json:"created,omitempty"`
	Source         *string `json:"source,omitempty"`
}

type Query struct {
}
