{{- if and .Values.postgresql.provisioning.enabled .Values.postgresql.backup.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: yaba-s3-creds
  namespace: {{ .Values.global.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: yaba-s3-creds
    creationPolicy: Owner
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: yaba/aws
        property: access_key_id
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: yaba/aws
        property: secret_access_key
{{- end }}
