# This is an easy out-of-the-box self-hosted config and comes with everything
# needed to run a yaba server.
#
# A `db_password.txt` file needs to be initialized without special characters or new lines.
#
# Docker compose setup that creates:
# - Postgres instance exposed on port 5432
# - Yaba instance exposed on port 9222 running in single user mode

# Load DB from the docker compose file.
include:
  - ../db/docker-compose.yml

services:
  yaba_server:
    image: wenbenz/yaba
    ports:
      - "80:80"
    env_file:
      - ../../env/docker.env
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password
    links:
      - db
    depends_on:
      - db
